In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("Yes! GPU is available")
  print("Using",torch.cuda.get_device_name(0))
else:
  print("No GPU")

Yes! GPU is available
Using Tesla T4


In [ ]:
device=torch.device('cuda')
import time

In [ ]:
size=10000
a_cpu=torch.rand(size,size)
b_cpu=torch.rand(size,size)
start_time=time.time()
result_cpu=torch.matmul(a_cpu,b_cpu)
cpu_time=time.time()-start_time
print("Using cpu->",cpu_time)
a_gpu=a_cpu.to(device)
b_gpu=b_cpu.to(device)
start_time=time.time()
result_gpu=torch.matmul(a_gpu,b_gpu)
torch.cuda.synchronize()
gpu_time=time.time()-start_time
print("Using gpu->",gpu_time)


Using cpu-> 17.19135355949402
Using gpu-> 0.6634371280670166


In [4]:
x = torch.tensor(6.7)  # Input feature  cgpa
y = torch.tensor(0.0)  # True label (binary)  no placement

w = torch.tensor(1.0,requires_grad=True)  # Weight
b = torch.tensor(0.0,requires_grad=True)

In [5]:
def binary_cross_entropy_loss(prediction,target):
  epsilon=1e-8
  prediction=torch.clamp(prediction,epsilon,1-epsilon)
  return -(target*torch.log(prediction)+(1-target)*torch.log(1-prediction))

In [6]:
z=w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [7]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [8]:
loss=binary_cross_entropy_loss(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [9]:
loss.backward()

In [10]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [26]:
X=torch.tensor([1,2,3,4],dtype=torch.float32,requires_grad=True)

In [27]:
X

tensor([1., 2., 3., 4.], requires_grad=True)

In [28]:
Y=X**2
Y

tensor([ 1.,  4.,  9., 16.], grad_fn=<PowBackward0>)

In [29]:
Z=torch.sin(Y).mean()
Z

tensor(0.0522, grad_fn=<MeanBackward0>)

In [30]:
Z.backward()

In [31]:
print(X.grad)

tensor([ 0.2702, -0.6536, -1.3667, -1.9153])
